/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecuaciones_de_segundo_grado;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author triwa
 */
public class formulario extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public formulario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IMAGEN = new javax.swing.JPanel();
        a_cuadratica = new javax.swing.JTextField();
        b_cuadratica = new javax.swing.JTextField();
        c_cuadratica = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        form_x1 = new javax.swing.JTextField();
        form_x2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        form_delta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 572));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setBackground(new java.awt.Color(60, 145, 194));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("ECUACIÓN DE SEGUNDO GRADO");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout TITULOLayout = new javax.swing.GroupLayout(TITULO);
        TITULO.setLayout(TITULOLayout);
        TITULOLayout.setHorizontalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TITULOLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(132, 132, 132))
        );
        TITULOLayout.setVerticalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TITULOLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        IMAGEN.setBackground(new java.awt.Color(204, 204, 204));
        IMAGEN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a_cuadratica.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        IMAGEN.add(a_cuadratica, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 91, -1));

        b_cuadratica.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        b_cuadratica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cuadraticaActionPerformed(evt);
            }
        });
        IMAGEN.add(b_cuadratica, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 80, -1));

        c_cuadratica.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        c_cuadratica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cuadraticaActionPerformed(evt);
            }
        });
        IMAGEN.add(c_cuadratica, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 80, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Δ  =");
        IMAGEN.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        form_x1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        form_x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_x1ActionPerformed(evt);
            }
        });
        IMAGEN.add(form_x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 312, -1));

        form_x2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        form_x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_x2ActionPerformed(evt);
            }
        });
        IMAGEN.add(form_x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 312, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("Graficar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        IMAGEN.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 510, 45));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.setAlignmentX(800);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        IMAGEN.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 151, -1));

        form_delta.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        form_delta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_deltaActionPerformed(evt);
            }
        });
        IMAGEN.add(form_delta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 95, -1));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setText("Calcular Soluciones ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        IMAGEN.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 510, 45));
        IMAGEN.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 106, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("x²    +");
        IMAGEN.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("X   +");
        IMAGEN.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("=  0");
        IMAGEN.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("X2  =");
        IMAGEN.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("X1  =");
        IMAGEN.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        getContentPane().add(IMAGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 670, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Double a = Double.parseDouble(a_cuadratica.getText());
        Double b = Double.parseDouble(b_cuadratica.getText());
        Double c = Double.parseDouble(c_cuadratica.getText());
        Double Delta;

        Delta = CalcularDelta(a, b, c);
        if (Delta > 0) {
            Double x1 = (-b + Math.sqrt(Delta)) / (2 * a);
            Double x2 = (-b - Math.sqrt(Delta)) / (2 * a);
            System.out.println("x1" + x1);
            System.out.println("x2" + x2);
            form_x2.setText(x2.toString());
            form_x1.setText(x1.toString());
        }
        if (Delta == 0) {
            Double x1 = -(b) / (2 * a);
            Double x2 = x1;
            System.out.println("x1" + x1);
            System.out.println("x2" + x2);
            form_x2.setText(x2.toString());
            form_x1.setText(x1.toString());
        }
        if (Delta < 0) {
            String i = "i";

            Double Preal = (-b) / (2 * a);
            Double Pimg = ((Math.sqrt(Math.abs(Delta)))) / (2 * a);
            String x1 = Preal + "+" + Pimg + i;
            String x2 = Preal + "-" + Pimg + i;
            System.out.println("x1" + x1);
            System.out.println("x2" + x2);
            form_x2.setText(x2.toString());
            form_x1.setText(x1.toString());
        }

        form_delta.setText(Delta.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void form_deltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_deltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_deltaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: Limpia cuadros

        a_cuadratica.setText(String.valueOf(""));
        b_cuadratica.setText(String.valueOf(""));
        c_cuadratica.setText(String.valueOf(""));

        form_delta.setText(String.valueOf(""));
        form_x1.setText(String.valueOf(""));
        form_x2.setText(String.valueOf(""));


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        double xx = Double.parseDouble(form_delta.getText());
        int d = (int) Math.round(xx);
        System.out.println(d);
        if (d < 0) {
            JOptionPane.showMessageDialog(null, "No puedo graficar una funcion imaginaria :(");
        } else {
            FunctionVisualizer fv = new FunctionVisualizer("fx");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void form_x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_x2ActionPerformed

    private void form_x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_x1ActionPerformed

    private void c_cuadraticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cuadraticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cuadraticaActionPerformed

    private void b_cuadraticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cuadraticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_cuadraticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formulario v1 = new formulario();
                v1.setVisible(true);
                v1.setLocationRelativeTo(null);
                v1.setResizable(false);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IMAGEN;
    private javax.swing.JPanel TITULO;
    public static javax.swing.JTextField a_cuadratica;
    public static javax.swing.JTextField b_cuadratica;
    public static javax.swing.JTextField c_cuadratica;
    private javax.swing.JTextField form_delta;
    private javax.swing.JTextField form_x1;
    private javax.swing.JTextField form_x2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    private Double CalcularDelta(Double a, Double b, Double c) {

        Double Delta;
        Delta = (Math.pow(b, 2)) - (4 * a * c);
        System.out.println("Delta" + Delta);
        return Delta;
    }
}
